# Generated by Django 5.1.2 on 2024-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
