# Generated by Django 5.1.2 on 2024-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12),
        ),
    ]
