# Generated by Django 5.1.2 on 2024-11-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_rename_proficiency_level_tutorsubject_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='frequency',
        ),
    ]
