# Generated by Django 5.1.2 on 2024-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_remove_requestsession_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12),
        ),
    ]
