# Generated by Django 5.1.2 on 2024-11-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_requestsession_frequency_requestsession_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='request_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.requestsession', unique=True),
        ),
    ]
