# Generated by Django 5.1.2 on 2024-11-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_alter_match_request_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='request_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorials.requestsession'),
        ),
    ]
