# Generated by Django 5.1.2 on 2024-11-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_alter_match_request_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSessionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15)),
                ('request_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tutorials.requestsession')),
            ],
        ),
    ]
