# Generated by Django 5.1.2 on 2024-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_requestsessionday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsession',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(0.5, 'Fortnightly'), (1, 'Weekly'), (2, 'Biweekly')], default=1),
        ),
    ]
