# Generated by Django 5.1.2 on 2024-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_alter_requestsession_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsession',
            name='frequency',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
