# Generated by Django 5.1.2 on 2024-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_alter_requestsession_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsession',
            name='date_requested',
            field=models.DateField(),
        ),
    ]
