# Generated by Django 5.1.2 on 2024-12-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_alter_requestsession_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.match', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
