# Generated by Django 5.1.2 on 2024-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_tutorsubject_price_alter_requestsession_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tutor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
