# Generated by Django 5.1.2 on 2024-12-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tutor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
