# Generated by Django 5.1.2 on 2024-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_invoice_bank_transfer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tutorsubject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='requestsession',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_request_per_student_subject'),
        ),
        migrations.AddConstraint(
            model_name='tutorsubject',
            constraint=models.UniqueConstraint(fields=('tutor', 'subject'), name='unique_tutor_subject'),
        ),
    ]
